### ISSUE TITLE
No such file or directory - in functions.php

### ISSUE THREAD

**Issue by JohnAJ** [jhornsby/djrequestapp#5]
functions/functions.php is included from /index.php, but has the line: -

```
include_once '../configuration.php';
```

which throws an error: -

include_once(../configuration.php) [function.include-once]: failed to open stream: No such file or directory in /path/to/requests/functions/functions.php on line 2

the include path is relative to the original document location, so should be: -

```
include_once 'configuration.php';
```

Not sure what knock-on effect this would have in admin, though, as the ../ version would be correct if included from admin/.

Might be best to simply include configuration.php from the original douments, rather than from functions/functions.php...?

**Comment by JTProjectFun** [comment]
I've seen this myself too - I should change any relative paths in the includes to something like:

`include_once (dirname(__DIR__).'/file_to_include.php'));`

which should fix the problem.

**Comment by JohnAJ** [comment]
```
include_once (dirname(__FILE__).'/file_to_include.php')); 
```

would be more compatible with earlier PHP versions (< 5.3) ;)

**Comment by JohnAJ** [comment]
Actually, that could still get messy including files from different sources / locations. How about early on in configuration.php (example): -

```
// full server path where app is installed
$requestappFileSystem = "/home/username/public_html/djrequestapp/";
```

and make any subsequent references to any included files start with this, e.g. (from public side index.php): -

```
include_once('configuration.php');
include_once($requestappFileSystem . 'login.php'); // Includes Login Script
include_once($requestappFileSystem . 'functions/functions.php');
```

or from admin/index.php: -

```
include_once('../configuration.php');
include_once($requestappFileSystem . 'admin/login.php'); // Includes Login Script
include_once($requestappFileSystem . 'functions/functions.php');
```

?

**Comment by JohnAJ** [comment]
And if doing that, best thing to do (IMHO) would be define the web root in configuration.php at the same time, e.g.: -

```
// full server path where app is installed
$requestappFileSystem = "/home/username/public_html/djrequestapp/";

// web dir where app is installed
$requestappWebDir = "http://domain.com/djrequestapp/";
```

Taking that setting out of admin....this would also easily allow the use of HTTPS if required.

**Comment by JTProjectFun** [comment]
Variables now used in config file, so we can close this
